### ISSUE TITLE
vehicle_factors is not an array

### ISSUE THREAD

**Issue by bu-ra3y** [SigoTechnologies/sigo-socotra-config#2]
Hey @iarambula, 

https://github.com/SigoTechnologies/sigo-socotra-config/blob/0daffb18e91bfeecbbd6c9eb80eb1fd12e0d435a/products/sigo-personal-auto/policy/exposures/vehicle/perils/bodily_injury.premium.liquid#L3

`vehicle_factors` is not turning out to be an array for me when I have 2 vehicles. I get:
`[ "0.6953310.862488" ]`
And I think I'm expecting
`[ 0.695331, 0.862488 ]`

In my testing it has to do with how you are working with the array.
I've found that you need to:
not initialize it at the start
check in the loop to see if it's initialized, and if not: handle the empty array case; if so, handle the non-empty array case.
I've not found a good initialization for arrays in Liquid.

**Comment by bu-ra3y** [comment]
This is one of the more concise ways I've come up with for building an array in a loop without initializing it outside the loop:
```
{%- assign separator = ", " %}
{%- for i in (1..3) %}
  {%- if arr %}
    {%- assign arr = arr | append:separator %}
  {%- endif %}
  {%- assign arr = arr | append: "value" %}
  {{ arr }}
{%- endfor %}
```

Try it here: https://liquidjs.com/playground.html#eyUtIGFzc2lnbiBzZXBhcmF0b3IgPSAiLCAiICV9CnslLSBmb3IgaSBpbiAoMS4uMykgJX0KICB7JS0gaWYgYXJyICV9CiAgICB7JS0gYXNzaWduIGFyciA9IGFyciB8IGFwcGVuZDpzZXBhcmF0b3IgJX0KICB7JS0gZW5kaWYgJX0KICB7JS0gYXNzaWduIGFyciA9IGFyciB8IGFwcGVuZDogInZhbHVlIiAlfQogIHt7IGFyciB9fQp7JS0gZW5kZm9yICV9Cg==

**Comment by bu-ra3y** [comment]
@iarambula I think I'm seeing the same thin with `driver_factors` being `["11"]` instead of `["1", "1"]`

**Comment by iarambula** [comment]
@bu-ra3y fixed both `driver_factors` and `vehicle_factors`.
